spring:
  profiles:
    active: local

---
spring:
  config:
    activate:
      on-profile: local

  datasource:
    url:
    username:
    password:
    #driver-class-name: com.tmax.tibero.jdbc.TbDriver
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  batch:
    jdbc:
      initialize-schema: never
      table-prefix: TDP_BATCH_

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    call-setters-on-nulls: true
    map-underscore-to-camel-case: true
    jdbc-type-for-null: NULL



