spring:
  config:
    activate:
      on-profile: local

  h2:
    console:
      enabled: true
      path: /h2-console # H2 데이터베이스의 웹 콘솔 기능 활성화

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./data/demo
    hikari:
      username: sa

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: never

server:
  port: 8080

